app_id: "6c8c662b-525b-43ec-84a1-ce55465274fe"
app_secret: "49VvI-PQBej4v_0j2sLv8-~u-NQ-g8M6l-"
redirect: "http://localhost:8000/callback"
scopes: "openid profile offline_access user.read "
authority: "https://login.microsoftonline.com"
authorize_endpoint: "/850aa78d-94e1-4bc6-9cf3-8c11b530701c/oauth2/v2.0/authorize"
token_endpoint: "/850aa78d-94e1-4bc6-9cf3-8c11b530701c/oauth2/v2.0/token"